### ISSUE TITLE
When I add the net35/Fleck2.dll into my project , it says referenced component could not be found?

### ISSUE THREAD

**Issue by vintage-coder** [peters/Fleck2#4]
In My Project, I need this Fleck2.dll  for websocket server implementation.
So, When i add this Fleck2.dll into my project, It raises Error as follows,
**Error	2	The type or namespace name 'Fleck2' could not be found (are you missing a using directive or an assembly reference?)	H:\ScanAppForWeb\NewScan\Form1.cs	1	7	NewScan
**

How Should I Solve this issues?
![test](https://user-images.githubusercontent.com/43435657/67073912-f149fb00-f13c-11e9-8472-8ddd7c98c69c.jpg)

Please Respond? Thanks in Advance.

**Comment by username1565** [comment]
I did already got this error, about namespace,
when I did try to compile [/demo/Fleck2.Demo.csproj](https://github.com/username1565/Fleck2/tree/master/demo)
by using the following string, in `Compile.bat`
```
%msbuild% /property:Configuration=Release Fleck2.Demo.csproj
```
So I just resolve this by adding [this string](https://github.com/username1565/Fleck2/blob/fcc6e26517b27e5a508f7d9c7eee619e1f81b5ea/demo/Compile.bat#L6):
```
%msbuild% /p:IntermediateOutputPath="../bin/Release/" /property:Configuration=Release Fleck2.Demo.csproj
```
And with parameter `/p:IntermediateOutputPath="../bin/Release/"` I don't see this warning.

Also, this [fork](https://github.com/git-thinh/Fleck2) can be compiled by opening Flick2.csproj, in Visual Studio 2010, without any warnings.

I think, you need to specify correct pathways, or write `using blah-blah;` in your Program,
or add Flick2 namespace in your program.

Hope this help you, because this repositary not updated from 2013, and contains some errors.
Have a nice day.

**P.S.:**
I did fix some errors, and now I have got successfully compilation `Flick2`
on `Windows XP` with `.NET Framework 4.0`.
I see working `Fleck2.Demo.exe` in `\demo\bin\Release\`
And after start this, it opening `client.html`, where I can chat with the server from browser.
I see sent messages in console on the server. So this is working.
Also, I see Fleck2.dll there.

You can repeat this steps too, just for fun, if you have free time:
1. Go to my fork: https://github.com/username1565/Fleck2
2. `Clone or Download` -> `Download zip`
3. Unzip.
4. Go to `demo/` and start `Compile.bat`, or start `/build.bat`.
5. Wait compilation.
6. Run `Fleck2.Demo.exe` from the folder `\demo\bin\Release\`.
7. Type any messages in opened `client.html`, and see this in the server console.

**Comment by vintage-coder** [comment]
T

> I did already got this error, about namespace,
> when I did try to compile [/demo/Fleck2.Demo.csproj](https://github.com/username1565/Fleck2/tree/master/demo)
> by using the following string, in `Compile.bat`
> 
> ```
> %msbuild% /property:Configuration=Release Fleck2.Demo.csproj
> ```
> 
> So I just resolve this by adding [this string](https://github.com/username1565/Fleck2/blob/fcc6e26517b27e5a508f7d9c7eee619e1f81b5ea/demo/Compile.bat#L6):
> 
> ```
> %msbuild% /p:IntermediateOutputPath="../bin/Release/" /property:Configuration=Release Fleck2.Demo.csproj
> ```
> 
> And with parameter `/p:IntermediateOutputPath="../bin/Release/"` I don't see this warning.
> 
> Also, this [fork](https://github.com/git-thinh/Fleck2) can be compiled by opening Flick2.csproj, in Visual Studio 2010, without any warnings.
> 
> I think, you need to specify correct pathways, or write `using blah-blah;` in your Program,
> or add Flick2 namespace in your program.
> 
> Hope this help you, because this repositary not updated from 2013, and contains some errors.
> Have a nice day.
> 
> **P.S.:**
> I did fix some errors, and now I have got successfully compilation `Flick2`
> on `Windows XP` with `.NET Framework 4.0`.
> I see working `Fleck2.Demo.exe` in `\demo\bin\Release\`
> And after start this, it opening `client.html`, where I can chat with the server from browser.
> I see sent messages in console on the server. So this is working.
> Also, I see Fleck2.dll there.
> 
> You can repeat this steps too, just for fun, if you have free time:
> 
> 1. Go to my fork: https://github.com/username1565/Fleck2
> 2. `Clone or Download` -> `Download zip`
> 3. Unzip.
> 4. Go to `demo/` and start `Compile.bat`, or start `/build.bat`.
> 5. Wait compilation.
> 6. Run `Fleck2.Demo.exe` from the folder `\demo\bin\Release\`.
> 7. Type any messages in opened `client.html`, and see this in the server console.

**Comment by vintage-coder** [comment]
Thanks username1565,

I fixed this issue. It is because of version incompatibility.
I used that fleck2 library into .net compact 2.0 smart device based Application.
It  works fine in windows desktop Application. that is .net framework 3.5 and above.
